---
- name: Disable UFW
  become: yes
  command: ufw disable

- name: Deny incoming traffic by default
  become: yes
  command: ufw default deny incoming

- name: Allow outgoing traffic by default
  become: yes
  command: ufw default allow outgoing

- name: Allow incoming ssh traffic
  become: yes
  command: ufw allow ssh

- name: Allow incoming traffic on configured ports
  become: yes
  command: ufw allow {{ item }}/tcp
  with_items: "{{ ports }}"

- name: Enable logging
  become: yes
  command: ufw logging on

- name: Enable UFW
  become: yes
  command: ufw --force enable
