---
- hosts: dokku
  vars:
    dokku_version: v0.14.0
    ports:
      - 80
      - 8080
  remote_user: "{{ admin_username }}"
  roles:
    - print_affected_hosts
    - upgrade_apt_packages
    - secure_server
    - install_dokku
  tasks:
  - name: Install dokku-dockerfile plugin
    become: yes
    command: dokku plugin:install https://github.com/mimischi/dokku-dockerfile.git
    args:
      creates: /var/lib/dokku/plugins/available/dockerfile
