---
- hosts: dokku
  vars:
    apps:
      - { name: back-end, static: no }
      - { name: docs, static: yes, port: 8080 }
      - { name: front-end, static: yes, port: 80 }
    dokku_version: v0.12.13
    public_keys:
      - { id: admin, key: azure_dokku_admin_rsa.pub }
      - { id: deploy, key: azure_dokku_git_rsa.pub }
  remote_user: "{{ admin_username }}"
  roles:
    - print_affected_hosts
    - upgrade_apt_packages
    - secure_server
    - install_dokku
    - configure_dokku_apps
  tasks:
  - name: Install dokku-dockerfile plugin
    become: yes
    command: dokku plugin:install https://github.com/mimischi/dokku-dockerfile.git
    args:
      creates: /var/lib/dokku/plugins/available/dockerfile
  - name: Configure dokku-dockerfile plugin
    command: dokku dockerfile:set back-end back-end/dockerfiles/deploy/Dockerfile
